# Generated by Django 4.2.6 on 2023-10-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=200)),
                ('user_state', models.CharField(max_length=100)),
                ('user_area', models.CharField(max_length=100)),
                ('user_postcode', models.CharField(max_length=10)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_education', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
