# Generated by Django 4.2.6 on 2023-11-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_property_profile_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_property',
            name='images',
            field=models.ImageField(upload_to='addproperty'),
        ),
    ]
