# Generated by Django 4.2.6 on 2023-11-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_district_division_upazila_district_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
    ]
